/**
 * Cloud Field Campaign Scorecard App v2
 * Design inspiré RoB Dashboard
 */

const API_BASE = 'http://localhost:8000/api/data';

let data = {
    summary: null,
    clouds: null,
    horseman: null,
    traffic: null,
    regional: null
};

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    console.log('App v2 initialized');
    loadData();

    // Event listeners
    document.getElementById('refreshBtn').addEventListener('click', loadData);
    document.getElementById('generateInsightsBtn').addEventListener('click', generateInsights);

    // Nav items
    document.querySelectorAll('.nav-item').forEach(item => {
        item.addEventListener('click', (e) => {
            e.preventDefault();
            document.querySelectorAll('.nav-item').forEach(nav => nav.classList.remove('active'));
            item.classList.add('active');
            // TODO: Switch views
        });
    });
});

// Load all data from API
async function loadData() {
    showLoading();

    try {
        const [summary, clouds, horseman, traffic, regional] = await Promise.all([
            fetch(`${API_BASE}/summary`).then(r => r.json()),
            fetch(`${API_BASE}/clouds`).then(r => r.json()),
            fetch(`${API_BASE}/horseman`).then(r => r.json()),
            fetch(`${API_BASE}/traffic`).then(r => r.json()),
            fetch(`${API_BASE}/regional`).then(r => r.json())
        ]);

        data = { summary, clouds, horseman, traffic, regional };

        renderSummaryStats();
        renderCloudCards();

        hideLoading();
    } catch (error) {
        console.error('Error loading data:', error);
        alert('Failed to load data. Make sure the API is running on localhost:8000');
        hideLoading();
    }
}

// Render Summary Stats
function renderSummaryStats() {
    const container = document.getElementById('summaryStats');

    const totalMDP = data.summary.total_mdp;
    const cloudCount = Object.keys(data.summary.cloud_breakdown).length;

    // Get top cloud
    let topCloud = { name: '', mdp: 0 };
    for (const [cloud, info] of Object.entries(data.summary.cloud_breakdown)) {
        if (info.mdp > topCloud.mdp) {
            topCloud = { name: cloud, mdp: info.mdp };
        }
    }

    // Calculate total horseman MDP for comparison
    const horsemanTotal = data.horseman.total.mdp || 0;

    const stats = [
        {
            icon: '💰',
            label: 'Total MDP',
            value: formatCurrency(totalMDP),
            change: null
        },
        {
            icon: '☁️',
            label: 'Clouds Tracked',
            value: cloudCount,
            change: null
        },
        {
            icon: '🏆',
            label: 'Top Cloud',
            value: topCloud.name,
            subvalue: formatCurrency(topCloud.mdp)
        },
        {
            icon: '📊',
            label: 'Leaders',
            value: data.regional.count,
            change: null
        }
    ];

    container.innerHTML = stats.map(stat => `
        <div class="stat-card">
            <div class="stat-icon">${stat.icon}</div>
            <div class="stat-label">${stat.label}</div>
            <div class="stat-value">${stat.value}</div>
            ${stat.subvalue ? `<div class="stat-change">${stat.subvalue}</div>` : ''}
            ${stat.change !== null ? `
                <div class="stat-change ${stat.change >= 0 ? 'positive' : 'negative'}">
                    ${stat.change >= 0 ? '↑' : '↓'} ${Math.abs(stat.change * 100).toFixed(1)}% YoY
                </div>
            ` : ''}
        </div>
    `).join('');
}

// Render Cloud Cards (Snapshots des scorecards)
function renderCloudCards() {
    const container = document.getElementById('cloudCards');

    const clouds = data.clouds.clouds.slice(0, 6); // Top 6 clouds

    container.innerHTML = clouds.map(cloud => {
        const yoyChange = cloud.avg_yoy_change;
        const isPositive = yoyChange >= 0;

        // Get breakdown for this cloud
        const regionalData = data.regional.data.filter(r => r.cloud === cloud.cloud);

        // Sample insights (mock for now - will be generated by Claude)
        const insights = getCloudInsights(cloud.cloud, cloud.mdp, yoyChange);

        return `
            <div class="cloud-card">
                <div class="cloud-card-header">
                    <div class="cloud-name">${cloud.cloud}</div>
                    ${yoyChange !== null ? `
                        <div class="cloud-badge ${isPositive ? 'badge-positive' : 'badge-negative'}">
                            ${isPositive ? '↑' : '↓'} ${Math.abs(yoyChange * 100).toFixed(1)}% YoY
                        </div>
                    ` : ''}
                </div>

                <div class="cloud-metrics">
                    <div class="metric">
                        <div class="metric-label">MDP</div>
                        <div class="metric-value">${formatCurrency(cloud.mdp)}</div>
                    </div>
                    <div class="metric">
                        <div class="metric-label">Leaders</div>
                        <div class="metric-value">${cloud.leaders_count}</div>
                    </div>
                </div>

                <div class="insights-section">
                    <div class="insight-group">
                        <div class="insight-title highlights">
                            🟢 Highlights
                        </div>
                        <ul class="insight-list">
                            ${insights.highlights.map(h => `<li class="insight-item">${h}</li>`).join('')}
                        </ul>
                    </div>

                    <div class="insight-group">
                        <div class="insight-title lowlights">
                            🔴 Areas to Watch
                        </div>
                        <ul class="insight-list">
                            ${insights.lowlights.map(l => `<li class="insight-item">${l}</li>`).join('')}
                        </ul>
                    </div>

                    <div class="insight-group">
                        <div class="insight-title actions">
                            📋 Next Steps
                        </div>
                        <ul class="insight-list">
                            ${insights.actions.map(a => `<li class="insight-item">${a}</li>`).join('')}
                        </ul>
                    </div>
                </div>
            </div>
        `;
    }).join('');
}

// Get cloud insights (mock - will be replaced by Claude API)
function getCloudInsights(cloud, mdp, yoyChange) {
    const insights = {
        Service: {
            highlights: [
                "Strong overall performance with +37% YoY growth across all regions",
                "Webinar channel driving 62% increase, now 8% of MDP share",
                "North region standout at +45% YoY"
            ],
            lowlights: [
                "Central performance declining -32% YoY",
                "AE contribution down -14% YoY",
                "Email growth marginal despite largest traffic source"
            ],
            actions: [
                "Launch 9 Service webinars in Q2",
                "Audit email offer mix with GIC team",
                "Optimize paid budget allocation"
            ]
        },
        Sales: {
            highlights: [
                "Webinar program delivering +44% growth",
                "North region strong at +45% YoY",
                "Demo content performing well organically"
            ],
            lowlights: [
                "Central decline -3% (excl. Switzerland impact)",
                "Paid search declining -31% YoY",
                "Organic traffic down -33% YoY"
            ],
            actions: [
                "Continue webinar momentum with Q2 lineup",
                "Launch on-demand paid programs",
                "Fix localized demo overwrite issues"
            ]
        },
        Marketing: {
            highlights: [
                "BDR contribution strong with double-digit growth",
                "Digital Specialist ramping at $16.4M",
                "Paid traffic up +57% YoY"
            ],
            lowlights: [
                "AE double-digit decline across 5 OUs",
                "Email 'other' offers down -23% YoY",
                "Organic and paid search declining"
            ],
            actions: [
                "Execute Q2 GIC BOM activation",
                "Build on CNX'26 momentum",
                "Follow up on SEM decline with paid team"
            ]
        }
    };

    // Return insights for this cloud or default
    return insights[cloud] || {
        highlights: [
            `MDP: ${formatCurrency(mdp)}`,
            yoyChange >= 0 ? `Growth trending positive at +${(yoyChange * 100).toFixed(1)}%` : 'Performance tracking enabled'
        ],
        lowlights: [
            yoyChange < 0 ? `YoY decline of ${(yoyChange * 100).toFixed(1)}%` : 'Monitor trends for optimization'
        ],
        actions: [
            'Review performance metrics',
            'Optimize channel mix'
        ]
    };
}

// Generate Insights with Claude
async function generateInsights() {
    try {
        const response = await fetch('http://localhost:8000/api/insights/example');
        const result = await response.json();

        alert(`AI Insights Generated!\n\nCloud: ${result.cloud}\n\nHighlights:\n${result.insights.highlights.join('\n')}\n\nAreas to Watch:\n${result.insights.areas_to_watch.join('\n')}`);

        // TODO: Update UI with generated insights
    } catch (error) {
        alert('Failed to generate insights. Make sure API is running.');
    }
}

// Utility Functions
function formatCurrency(value) {
    if (!value) return '$0';
    if (value >= 1000000) {
        return `$${(value / 1000000).toFixed(1)}M`;
    }
    return `$${(value / 1000).toFixed(0)}K`;
}

function showLoading() {
    document.body.classList.add('loading');
}

function hideLoading() {
    document.body.classList.remove('loading');
}
